//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace MvcTest.Models.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class holidays
    {
        [DisplayName("Дата")]
        public System.DateTime day_time { get; set; }
        [DisplayName("Событие")]
        public string desc { get; set; }
    }
}
